## Sectors identification

In [1]:
import pandas as pd

# Load edge list
edges = pd.read_csv("bluesky_large_edges_unweighted_10000 (1).csv")

# Extract unique tickers
tickers = pd.unique(
    pd.concat([edges["source"], edges["target"]], ignore_index=True)
)

ticker_df = pd.DataFrame({
    "ticker": sorted(tickers)
})

print(f"Number of unique tickers: {len(ticker_df)}")
display(ticker_df.head())

Number of unique tickers: 6243

  ticker
0      A
1     AA
2  AACOU
3   AADX
4    AAL

In [2]:
!pip install yfinance

Requirement already satisfied: yfinance in c:\users\elena\anaconda3\lib\site-packages (1.4.1)
Requirement already satisfied: pandas>=1.3.0 in c:\users\elena\anaconda3\lib\site-packages (from yfinance) (2.3.3)
Requirement already satisfied: numpy>=1.16.5 in c:\users\elena\anaconda3\lib\site-packages (from yfinance) (2.3.5)
Requirement already satisfied: requests>=2.31 in c:\users\elena\anaconda3\lib\site-packages (from yfinance) (2.32.5)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\elena\anaconda3\lib\site-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\elena\anaconda3\lib\site-packages (from yfinance) (4.5.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\elena\anaconda3\lib\site-packages (from yfinance) (2025.2)
Requirement already satisfied: peewee>=3.16.2 in c:\users\elena\anaconda3\lib\site-packages (from yfinance) (4.1.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\elena\anaconda3\lib\site-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.15 in c:\users\elena\anaconda3\lib\site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\elena\anaconda3\lib\site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in c:\users\elena\anaconda3\lib\site-packages (from yfinance) (16.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\elena\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\elena\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in c:\users\elena\anaconda3\lib\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\elena\anaconda3\lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.6.17)
Requirement already satisfied: rich in c:\users\elena\anaconda3\lib\site-packages (from curl_cffi>=0.15->yfinance) (14.2.0)
Requirement already satisfied: pycparser in c:\users\elena\anaconda3\lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.23)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\elena\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\elena\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\elena\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\elena\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\elena\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\elena\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\elena\anaconda3\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\elena\anaconda3\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\elena\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)

In [3]:
import yfinance as yf
import pandas as pd
from tqdm.auto import tqdm

tqdm.pandas()

def get_metadata(ticker):
    try:
        info = yf.Ticker(ticker).info

        return pd.Series({
            "company": info.get("longName"),
            "sector": info.get("sector"),
            "industry": info.get("industry"),
            "country": info.get("country"),
            "exchange": info.get("exchange")
        })

    except Exception:
        return pd.Series({
            "company": None,
            "sector": None,
            "industry": None,
            "country": None,
            "exchange": None
        })

metadata = ticker_df["ticker"].progress_apply(get_metadata)

ticker_metadata = pd.concat([ticker_df, metadata], axis=1)

  0%|          | 0/6243 [00:00<?, ?it/s]

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MKC.V"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: NE.W"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PBR.A"}}}

In [4]:
#Controlla quanti sticker sono stati trovati senza settore
missing = ticker_metadata["sector"].isna().sum()

print(f"Tickers without sector: {missing}/{len(ticker_metadata)}")

ticker_metadata[ticker_metadata["sector"].isna()].head(20)

Tickers without sector: 1119/6243

,ticker,company,sector,industry,country,exchange
7,AAOG,Leverage Shares 2X Long AAOI Daily ETF,None,None,None,BTS
10,AAOX,Tradr 2X Long AAOI Daily ETF,None,None,None,BTS
12,AAPD,Direxion Daily AAPL Bear 1X Shares,None,None,None,NGM
18,AAXJ,iShares MSCI All Country Asia ex Japan ETF,None,None,None,NGM
27,ABI,VictoryShares Pioneer Asset-Based Inc ETF,None,None,None,NGM
28,ABLD,Abacus FCF ETF Trust - Abacus FCF Real Assets ...,None,None,None,BTS
78,ACWI,iShares MSCI ACWI ETF,None,None,None,NGM
79,ACWX,iShares MSCI ACWI ex U.S. ETF,None,None,None,NGM
126,AETH,Bitwise Trendwise Ethereum & Treasuries Rotati...,None,None,None,PCX
133,AFK,VanEck Africa Index ETF,None,None,None,PCX
141,AGG,iShares Core U.S. Aggregate Bond ETF,None,None,None,PCX
144,AGIX,KraneShares Artificial Intelligence and Techno...,None,None,None,NGM
153,AGQ,ProShares Ultra Silver,None,None,None,PCX
158,AGZ,iShares Agency Bond ETF,None,None,None,PCX
164,AIA,iShares Asia 50 ETF,None,None,None,NGM
168,AIEQ,Amplify AI Powered Equity ETF,None,None,None,PCX
183,AIQ,Global X Artificial Intelligence & Technology ETF,None,None,None,NGM
189,AIRR,First Trust RBA American Industrial Renaissanc...,None,None,None,NGM
191,AIS,VistaShares Artificial Intelligence Supercycle...,None,None,None,PCX
196,AIVC,Amplify Bloomberg AI Value Chain ETF,None,None,None,PCX

In [5]:
# salva il dataset in un file CSV
ticker_metadata.to_csv("ticker_metadata.csv", index=False)
print ("Ticker metadata saved to ticker_metadata.csv")

Ticker metadata saved to ticker_metadata.csv

In [6]:
import os

print(os.path.exists("ticker_metadata.csv"))

True

In [7]:
import pandas as pd

df = pd.read_csv("ticker_metadata.csv")
df.head()

,ticker,company,sector,industry,country,exchange
0,A,"Agilent Technologies, Inc.",Healthcare,Diagnostics & Research,United States,NYQ
1,AA,Alcoa Corporation,Basic Materials,Aluminum,United States,NYQ
2,AACOU,Abony Acquisition Corp. I,Financial Services,Shell Companies,United States,NGM
3,AADX,"Applied Aerospace & Defense, Inc.",Industrials,Aerospace & Defense,United States,NYQ
4,AAL,American Airlines Group Inc.,Industrials,Airlines,United States,NMS

In [8]:
print(df.shape)
print(df.columns)

(6243, 6)
Index(['ticker', 'company', 'sector', 'industry', 'country', 'exchange'], dtype='object')

In [9]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6243 entries, 0 to 6242
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ticker    6243 non-null   object
 1   company   6157 non-null   object
 2   sector    5091 non-null   object
 3   industry  5091 non-null   object
 4   country   5124 non-null   object
 5   exchange  6235 non-null   object
dtypes: object(6)
memory usage: 292.8+ KB
None